### ISSUE TITLE
Compile error on build .27

### ISSUE THREAD

**Issue by Tsoccerguy3** [Mestre-Tramador/Mo-Creatures-Redux-Redone#2]
I saw your project and tried to compile to see how far along the mod is . I got a compile error , there is 1 mistake i can see . Is these close to a A alpha build for testing ?

D:\Dev\mcre2>gradlew build
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/4.10.3/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Configure project :
Java: 1.8.0_281 JVM: 25.281-b09(Oracle Corporation) Arch: amd64
New Dep: net.minecraftforge:forge:1.16.4-35.1.0_mapped_snapshot_20201028-1.16.3

> Task :compileJava
2021-03-14 15:46:49,867 Task worker for ':' WARN Advanced terminal features are not available in this environment
Note: SpongePowered MIXIN Annotation Processor Version=0.8.2
Note: ObfuscationServiceMCP supports type: "searge"
Note: ObfuscationServiceMCP supports type: "notch"
D:\Dev\mcre2\src\main\java\mestretramador\rrmocreatures\data\common\provider\loot\RRMoCBlockLootTablesProvider.java:96: error: cannot find symbol
            Map.entry(RegisterBlock.OGRE_LAIR_GRASS.returnAsBlock(), RegisterBlock.OGRE_LAIR_DIRT.returnAsBlock()),
               ^
  symbol:   method entry(Block,Block)
  location: interface Map
D:\Dev\mcre2\src\main\java\mestretramador\rrmocreatures\data\common\provider\loot\RRMoCBlockLootTablesProvider.java:97: error: cannot find symbol
            Map.entry(RegisterBlock.WYVERN_LAIR_GRASS.returnAsBlock(), RegisterBlock.WYVERN_LAIR_DIRT.returnAsBlock())
               ^
  symbol:   method entry(Block,Block)
  location: interface Map
2 errors

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 15s
1 actionable task: 1 executed

**Comment by Mestre-Tramador** [comment]
Hello, my friend Tsoccerguy3! First of all, thanks to passing by and giving your feedback! I'd never imagine someone doing it in some amateur random programmer repository, hehehe...

Well, about the compile error, it's strange, because it not occured on my environment. I assume it can be related to the IDE (I use VSCode), my experience with gradle is not of the best one, and will not confirm anything... But be sure that I will look for this error and fix it when I found it! :]

About the Alpha Version, I still not believe that I reach this far, hehehe, so every step is counting to me! Feel free to follow the repository and watch for it, I work on this code whenever I can, I also conciliate with my work, my studies, my writing, and my other repositories, sort of busy life, hehehe...

Be safe, my friend, and have faith in your code!
